// resources/assets/js/Vue/App.vue
<template>
    <div class="ui container">
        <Post :post="post"></Post>
    </div>
</template>

<script>
import { posts } from '@/api.js';
import Post from './Post.vue';

export default {
    components: {
        Post
    },
    data() {
        return {
            post: {}
        };
    },
    mounted() {
        posts.find(1).then(response => {
            console.log('Teste de API:');
            console.log(response.data);

            this.post = response.data;
        });
    }
};
</script>

// resources/assets/js/React/App.js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';

import { posts } from '@/api.js';
import Post from './Post.js';

export default class App extends Component {


    constructor(props) {
        super(props);
        this.state = {
            post: {}
        };

        posts.find(1).then(response => {
            console.log('Teste de API:');
            console.log(response.data);

            this.setState({ post: response.data });
        });
    }

    render() {
        return (
            <div className="container">
                {this.state.post ? (<Post post={this.state.post}></Post>) : 'a'}
            </div>
        );
    }
}
